# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d053ede4533bd4686f628cdcb34311cce54045e3eb8fb2d1d2d2c5cc738ae8280403d408368272b5491ed817ceeda6198c2c94868d1869b944c12d2d202c7ed5

test:
  secret_key_base: 43909278a5575d0ab113e80f4e7e0eb4c4a6f88aae321a7974d35534f75d33a5cd11f907956024143b6416756e53d213ec87f4f68a6ed7694ab548b4d094bdc7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
